ReminderSystem: ReminderSystem.o
	gcc ReminderSystem.o -o ReminderSystem

ReminderSystem.o: ReminderSystem.c ReminderSystem.h
	gcc -c ReminderSystem.c -o ReminderSystem.o

clean: 
	rm *.o ReminderSystem 
